config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :form_models, param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rad_check_group.rb
class RadCheckGroup < ApplicationRecord
  validates :groupname, :attr, :op, :value, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/form_models_controller.rb
class FormModelsController < ApplicationController
  before_action :set_form_model, only: [:show, :edit, :update, :destroy]

  # GET /form_models
  # GET /form_models.json
  def index
    @form_models = FormModel.all
  end

  # GET /form_models/1
  # GET /form_models/1.json
  def show
  end

  # GET /form_models/new
  def new
    @form_model = FormModel.new
  end

  # GET /form_models/1/edit
  def edit
  end

  # POST /form_models
  # POST /form_models.json
  def create
    @form_model = FormModel.new(form_model_params)

    respond_to do |format|
      if @form_model.save
        format.html { redirect_to @form_model, notice: 'Form model was successfully created.' }
        format.json { render :show, status: :created, location: @form_model }
      else
        format.html { render :new }
        format.json { render json: @form_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_models/1
  # PATCH/PUT /form_models/1.json
  def update
    respond_to do |format|
      if @form_model.update(form_model_params)
        format.html { redirect_to @form_model, notice: 'Form model was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_model }
      else
        format.html { render :edit }
        format.json { render json: @form_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_models/1
  # DELETE /form_models/1.json
  def destroy
    @form_model.destroy
    respond_to do |format|
      format.html { redirect_to form_models_url, notice: 'Form model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_model
      @form_model = FormModel.find(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_model_params
      params.fetch(:form_model).permit(:name, :time_limit, :download_limit, :upload_limit, :cleartext_password)
          .merge(slug: params[:form_model][:name].parameterize)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_models_helper.rb
module FormModelsHelper
end

app/views/form_models/_form.html.erb
<%= form_for(@form_model) do |f| %>
  <% if form_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form_model.errors.count, "error") %> prohibited this form_model from being saved:</h2>

      <ul>
      <% form_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= text_field_tag '[form_model]name', @form_model.name %>
  <%= text_field_tag '[form_model]time_limit', @form_model.time_limit %>
  <%= text_field_tag '[form_model]download_limit', @form_model.download_limit %>
  <%= text_field_tag '[form_model]upload_limit', @form_model.upload_limit %>
  <%= text_field_tag '[form_model]cleartext_password', @form_model.upload_limit %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/form_models/edit.html.erb
<h1>Editing Form Model</h1>

<%= render 'form', form_model: @form_model %>

<%= link_to 'Show', @form_model %> |
<%= link_to 'Back', form_models_path %>

app/views/form_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Form Models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time Limit</th>
      <th>Download Limit</th>
      <th>Upload Limit</th>
      <th>ACTIONS</th>
    </tr>

  </thead>

  <tbody>
    <% @form_models.each do |form_model| %>
      <tr>
        <td><%= form_model.name%></td>
        <td><%= form_model.time_limit%></td>
        <td><%= form_model.download_limit%></td>
        <td><%= form_model.upload_limit%></td>
        <td>
          <%= link_to 'Show', form_model_path(form_model, slug: form_model.slug) %>
          <%= link_to 'Edit', edit_form_model_path(form_model, slug: form_model.slug) %>
          <%= link_to 'Destroy', form_model, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form Model', new_form_model_path %>

app/views/form_models/new.html.erb
<h1>New Form Model</h1>

<%= render 'form', form_model: @form_model %>

<%= link_to 'Back', form_models_path %>

app/views/form_models/show.html.erb
<p id="notice"><%= notice %></p>

NAME: <%= @form_model.name %><br>
TIME LIMIT: <%= @form_model.time_limit %><br>
DOWNLOAD LIMIT: <%= @form_model.download_limit %><br>
UPLOAD LIMIT: <%= @form_model.upload_limit %><br>

<%= link_to 'Edit', edit_form_model_path(@form_model, slug: @form_model.slug) %> |
<%= link_to 'Back', form_models_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Radgroup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>